const os=require('os')
// console.log(os.arch())
const dd=os.freemem()
console.log(dd)
const dd1=os.totalmem()
console.log(dd1)
console.log(os.arch())
console.log(os.hostname())
console.log(os.platform())
console.log(os.tmpdir())
console.log(os.type())